---
- name: set defaults (user/group/paths) for further installations
  include: set-defaults.yml

- name: LOOP to install prometheus components
  include: loop-exporter.yml
    component="{{ item }}"
  with_items:
    - "{{ prometheus_components }}"

# offene todos:
# - systemd unit files löschen wenn falsch
# - alte executables löschen
# - force reinstall
